; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32doit-devkit-v1]
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0

upload_protocol = esptool
upload_port = COM62

;upload_protocol = espota
;upload_port = s3serpentine.local
;upload_flags = 
;    --auth=OTA_default_pass1

monitor_speed = 115200
monitor_port = COM62
lib_deps = 
    adafruit/Adafruit NeoPixel@^1.10.4
    adafruit/Adafruit AHTX0@^2.0.5


[platformio]
;extra_configs = platformio_override.ini